### ISSUE TITLE
stuck at "This will wipe your db, are you sure you want to reinstall?"

### ISSUE THREAD

**Issue by dulhaver** [emadshaaban92/docker-compose-erpnext#2]
... I have confirmed with `y` and nothing seems to be happening beyond that point. 

![image](https://user-images.githubusercontent.com/7608112/28162890-6533c564-67fb-11e7-98b8-aa8ecac4bdb8.png)
My connection to docker.com can be awfully slow here from China but I guess it's not even involved at this point of the setup, right?

I'll leave it another hour and then will try to just run `docker-compose -f manage.yml run setup` once again and see whether it's just a hickup

**Comment by dulhaver** [comment]
aborted the first attempt running `docker-compose -f manage.yml run setup`

again I do not get further then before (stuck after agreeing to `wipe my database and reinstall`)
am I alone with that?

**Comment by dulhaver** [comment]
seems it's a matter of taking forever .... just an eternity or so later I noted that I passed the reinstall of the database. going further with `docker-compose up -d` now and closing this issue

**Comment by emadshaaban92** [comment]
Yes it's not related to your connection to docker.com, the image is already pulled.
It maybe related to docker storage driver, I'll investigate more into it.

**Comment by clefavelli** [comment]
$ docker-compose -f manage.yml run setup
Creating network "docker-compose-erpnext_default" with the default driver
Creating erpnext-db ... done
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 277, in _use
    use(site, sites_path=sites_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 280, in use
    with open(os.path.join(sites_path,  "currentsite.txt"), "w") as sitefile:
IOError: [Errno 13] Permission denied: u'./currentsite.txt'

I get this error when I run setup

followed by 

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 133, in reinstall
    _reinstall(site, admin_password, yes, verbose=context.verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 153, in _reinstall
    install_apps=installed, admin_password=admin_password)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 62, in _new_site
    installing = touch_file(get_site_path('locks', 'installing.lock'))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/__init__.py", line 332, in touch_file
    with open(path, 'a'):
IOError: [Errno 13] Permission denied: u'./localhost/locks/installing.lock'
Setup Finished
