### ISSUE TITLE
got error on 1st install

### ISSUE THREAD

**Issue by wellart** [emadshaaban92/docker-compose-erpnext#4]
here the error log
`Status: Downloaded newer image for bizzotech/erpnext:latest
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 277, in _use
    use(site, sites_path=sites_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 280, in use
    with open(os.path.join(sites_path,  "currentsite.txt"), "w") as sitefile:
IOError: [Errno 13] Permission denied: u'./currentsite.txt'
Waiting for DB to start up
2017/12/27 11:39:00 Waiting for: tcp://db:3306
2017/12/27 11:39:00 Connected to tcp://db:3306
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 133, in reinstall
    _reinstall(site, admin_password, yes, verbose=context.verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 153, in _reinstall
    install_apps=installed, admin_password=admin_password)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 62, in _new_site
    installing = touch_file(get_site_path('locks', 'installing.lock'))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/__init__.py", line 332, in touch_file
    with open(path, 'a'):
IOError: [Errno 13] Permission denied: u'./localhost/locks/installing.lock'
Setup Finished`

**Comment by robvdl** [comment]
Yeah same for me, it's broken, I followed the instructions perfectly from the README.

**Comment by robvdl** [comment]
But why on earth is it running on Python 2, ERPNext supports both Python 3 and 2 but 3 is recommended for version 11.

u'./localhost/locks/installing.lock' the u is telling me this is Python 2.

**Comment by clefavelli** [comment]
Should I assume that the support for erpnext is low and poor given the number of errors one encounters in trying to set up ,seems like there are no solutions

**Comment by madmath03** [comment]
@clefavelli More like they go too fast fixing business features to update / complete their technical documentation...
They have new releases almost every 2 days, but support for Python 3 only comes with ERPNext 11 (version 10 was last updated only 6 months ago) and there has not yet been a new release of bench officially supporting Python 3 for production : https://github.com/frappe/bench#1-install-pre-requisites

> Python 2.7 [Python3.5+ also supported, but not recommended for production]

I'm currently trying to build an updated version of this repository's containers: 
* https://github.com/Monogramm/docker-erpnext
* https://github.com/Monogramm/docker-frappe

It's still in progress but I hope to get this working by the end of this week with some docker-compose in travis to check everything.
Any help to test it then will be welcome 😉

**Comment by emadshaaban92** [comment]
@wellart @robvdl @clefavelli  

I'm so sorry for the very late reply and for any inconvenience happened because of this repo. As far as I remember, it was working but at that time ERPNext was evolving very fast and any tooling would need so much maintenance. Anyway, I stopped using ERPNext long time ago and simply abandoned everything related to it. 

I should have updated the README to reflect that which I will do now, I'm sorry again.

And thanks @madmath03 for your progress to make things work. :+1:
